---
output:
  html_document:
    css: style.css
---
------


```{r comment=NA, error = FALSE, warning=FALSE, message=FALSE, results = "asis", echo=FALSE}
cprint <- function(contents, type){
  if (type == "h1") {
    cat(sprintf("<h1> %s </h1>", contents))  
  } else if(type == "h2"){
    cat(sprintf("<h2> %s </h2>", contents))  
  } else if(type == "h3"){
    cat(sprintf("<h3> %s </h3>", contents))  
  } else if(type == "h4"){
    cat(sprintf("<h4> %s </h4>", contents))  
  } else if(type == "h5"){
    cat(sprintf("<h5> %s </h5>", contents))  
  } else{
    cat(sprintf("%s", contents))  
  }
  cat("<hr>")
}

insert_chart_application <- function(school_index, year_value){
  cprint("모집인원 | 기본계획", subject_print_type)
  
  # 모집인원 pie chart
  selected_data_pie <- raw_data_pie %>% filter(schoolindex == school_index & year == year_value)
  selected_data_pie <- gather(selected_data_pie,,,-1)
  pie <- ggplot(selected_data_pie,aes(x='',y=value,fill=key)) + geom_bar(width = 1, stat = 'identity')
  pie <- pie+coord_polar('y',start=0)
  blank_theme <- theme_minimal()+
    theme(
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.border = element_blank(),
      panel.grid=element_blank(),
      axis.ticks = element_blank(),
      plot.title=element_text(size=14, face="bold")
    )
  
  pie <- pie + scale_fill_grey() + blank_theme +  theme(axis.text.x=element_blank())
  
  # table plot
  if (school_index <= 15) {
    raw_data_table <- raw_data_table_part1
  }else{
    raw_data_table <- raw_data_table_part2
  }
  
  selected_data_table <- raw_data_table %>% filter(schoolindex == school_index & year == year_value) %>%   select(level,leet,gpa,lang,doc,essay,interview,sum)
  selected_data_table[is.na(selected_data_table)] <- 0
  
  # pie 랑 table 결합 
  grid.arrange(pie,tableGrob(selected_data_table, rows = NULL),nrow=1)
}

# 남녀 비율
insert_chart_sex <- function(school_index, year_value){
  cprint("남녀 비율", subject_print_type)

  selected_data_sex <- gather(raw_data_sex %>% filter(schoolindex == school_index) %>% select(selected_colname_sex))
  selected_data_sex <- selected_data_sex %>% mutate(group=substr(key,1,1),year=substr(key,2,3))
  ggplot(selected_data_sex,aes(x=year, y=value, fill = group)) + geom_bar(stat='identity', position = 'dodge')
}

# 자교 비율
insert_chart_myschool <- function(school_index, year_value){
  cprint("자교 비율", subject_print_type)

  selected_data_myschool <- gather(raw_data_myschool %>% filter(schoolindex == school_index) %>% select(selected_colname_myschool))
  selected_data_myschool <- selected_data_myschool %>% mutate(group=substr(key,1,1),year=substr(key,2,3))
  ggplot(selected_data_myschool,aes(x=year, y=value, fill = group)) + geom_bar(stat='identity', position = 'dodge')
}

insert_chart_foreign <- function(school_index, year_value){
  cprint("외국대학 출신 학생 수", subject_print_type)
  
  foreign <- gather(raw_data_foreign %>% filter(schoolindex == school_index) %>% select(selected_colname_foreign))
  
  p <- ggplot(foreign,aes(key,value)) + geom_bar(stat='identity')
  p + theme_minimal()

}

insert_school_name <- function(school_index, year_value){
  school_name <- c("강원대", "건국대", "경북대", "경희대", "고려대", "동아대", "부산대", "서강대", "서울대", "서울시립대", "성균관대", "아주대", "연세대", "영남대", "원광대", "이화여대", "인하대", "전남대", "전북대", "제주대", "중앙대", "충남대", "충북대", "한국외대", "한양대")
  cprint(school_name[school_index], school_name_print_type)

}

insert_chart_age_rate <- function(school_index, year_value){
  cprint("연령 비율", subject_print_type)
  
  selected_data_age_rate <- raw_data_age %>% filter(schoolindex == school_index) %>% select(ends_with('14'),ends_with('15'),ends_with('16'),ends_with('17')) %>% gather()
  selected_data_age_rate <- selected_data_age_rate %>% mutate(group = substr(key,1,1),year = substr(key,2,3))

selected_data_age_rate <- selected_data_age_rate %>% ggplot(aes(year,value,fill=group)) + geom_bar(stat = 'identity')
selected_data_age_rate + theme_classic()

}

insert_chart_major <- function(school_index, year_value){
  
selected_data_major <- gather(raw_data_major[1,])
selected_data_major <- selected_data_major %>% filter(key == 'law' | key == 'human' | key == 'nature')
selected_data_major <- ggplot(selected_data_major,aes(x='',y=value,fill=key)) + geom_bar(width = 1, stat = 'identity')
selected_data_major <- selected_data_major+coord_polar('y',start=0)
selected_data_major

}

```

```{r comment=NA, error = FALSE, warning=FALSE, message=FALSE, results = "asis", echo=FALSE}


library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)

# 변수 선언 부분
school_index <- 1
year_value <- 2018
school_name_print_type <- "h1"
subject_print_type <- "h3"

colname_prefix_sex <- c("m","w")
colname_prefix_myschool <- c("m","o")
colname_prefix_foreign <- c("f")
year_prefix <- as.numeric(substr(year_value,3,4)) - 4
selected_colname_sex <- NULL
selected_colname_myschool <- NULL
selected_colname_foreign <- NULL
for (i in 0:3) {
  selected_colname_sex <- c(selected_colname_sex, paste(colname_prefix_sex,year_prefix+i, sep=""))
  selected_colname_myschool <- c(selected_colname_myschool, paste(colname_prefix_myschool,year_prefix+i, sep=""))
  selected_colname_foreign   <- c(selected_colname_foreign, paste(colname_prefix_foreign,year_prefix+i, sep=""))
}
  
# 본문 시작
  raw_data_pie <- read.csv('./rawdatas/application.csv')
  raw_data_table_part1 <- read.csv('./rawdatas/reflection_part1.csv')
  raw_data_table_part2 <- read.csv('./rawdatas/reflection_part2.csv')
  raw_data_sex <- read.csv('./rawdatas/sex.csv')%>% rename(schoolindex = 癤퓋choolindex)
  raw_data_myschool <- read.csv('./rawdatas/myschool.csv')%>% rename(schoolindex = 癤퓋choolindex)
  raw_data_foreign <- read.csv('./rawdatas/foreign.csv')  %>% rename(schoolindex = 癤퓋choolindex)
  raw_data_age <- read.csv('./rawdatas/age.csv')
  raw_data_major <- read.csv('./rawdatas/major.csv')
  
  
  for (school_index in 1:5) {
    insert_school_name(school_index, year_value)
    insert_chart_application(school_index, year_value)
    print(insert_chart_sex(school_index, year_value))
    print(insert_chart_myschool(school_index, year_value))
    print(insert_chart_foreign(school_index, year_value))
    print(insert_chart_age_rate(school_index, year_value))
    print(insert_chart_major(school_index, year_value))
  }
  
  
```
