---
header-includes:
- \usepackage{kotex}

output: 
  pdf_document:
    latex_engine: xelatex
lang: korean
mainfont: KoPubBatangLight
geometry: margin=1in

---
```{r, include=FALSE, message = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo = FALSE, dev ="cairo_pdf")

library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(ggpubr)
library(extrafont)
library(gridExtra)
library(grid)
library(downloader)
library(grDevices)

loadfonts()
```





```{r comment=NA, error = FALSE, warning=FALSE, message=FALSE, results = "asis", echo=FALSE}


#####################################################
#                   모집인원 파이 차트 +기본계획 표
#####################################################
cat("\n\n")
cat("\n# 1. 모집인원 파이차트 + 기본 계획표 \n")
cat("\n\n")

entrance <- read.csv('./rawdatas/application.csv') %>% 
  filter(schoolindex == 1 & year == 2018) %>% select(3:7) %>% rename()%>% gather() %>%
  filter(value != 0) %>% arrange(desc(value)) %>% mutate(text_y = cumsum(value) - value/2)

entrance$key <- factor(entrance$key,levels = rev(as.character(entrance$key)))

mojip_plot <- ggplot(entrance,aes(x='',y=value,fill=key)) + geom_bar(width = 1,stat = 'identity', color = 'white') + 
  coord_polar(theta = 'y', start = 0 ) + 
  theme_minimal() + 
  theme(axis.title = element_blank(), axis.text = element_blank(), 
        panel.grid = element_blank(), legend.position = 'bottom', 
        legend.title = element_blank(),legend.text = element_text(family="KoPubBatang Light")) + 
  guides(fill = guide_legend(reverse = TRUE))+ 
  geom_text(aes(label = value, y = text_y), nudge_x = .7, family="KoPubBatang Light") + 
  scale_fill_grey(start = 0.8, end = 0.2)

# p + scale_fill_manual(values = c('#FFCCFF','#FF99CC','#FF3399','#FF33FF','#FF00FF','#FF00CC'))


#기본계획 표 : standard

standard <- read.csv('./rawdatas/entrance_standard.csv') %>% 
  filter(schoolindex == 1 & year == 2018) %>% 
  select(level,leet,gpa,lang,doc,essay,interview,sum) %>% 
  replace(.,is.na(.),0)
standard_table <- ggtexttable(standard, rows = NULL, theme = ttheme(base_size=5 ,tbody.style = tbody_style(fill = 'white'), ))

# pie 랑 table 합체 

#ggarrange(mojip,standard_table,ncol = 2, nrow = 1)
grid.arrange(mojip_plot, standard_table, ncol = 2)



###########################################
#                   sexplot 남녀비율 막대그래프
############################################
cat("\n\n")
cat("\n# 2. 남녀비율 막대그래프 \n")
cat("\n\n")

sexdata <- read.csv('./rawdatas/sex.csv') %>% 
  rename(schoolindex = 癤퓋choolindex) %>% 
  filter(schoolindex == 1) %>% 
  select(m14, w14, m15, w15, m16, w16, m17, w17)

sexdata1 <- gather(sexdata) %>% mutate(group=substr(key,1,1),year=substr(key,2,3))

sexplot <- ggplot(sexdata1,aes(x=year, y=value, fill = group)) + geom_bar(stat='identity', position = 'dodge', width = 0.5)+
  geom_text(aes(x=year, y=value, label = value),vjust=-0.5, position = position_dodge(0.5),
            family="KoPubBatang Light") + 
  theme(legend.position="bottom", legend.direction="horizontal", 
        legend.title = element_blank()) + 
  scale_fill_manual(values = c('#FF00FF','#FFCCFF'), labels = c('남','여')) +
  scale_x_discrete(labels=seq(2014,2017,1))+
  theme_minimal() + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank(), 
        panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(color = 'gray'), 
        panel.grid.minor.y = element_line(color='gray'), axis.ticks = element_blank(), 
        axis.text.y = element_blank(),legend.text = element_text(family="KoPubBatang Light"))
sexplot



###########################################
#                   myschoolbarplot 자교비율 막대그래프 
############################################
cat("\n\n")
cat("\n# 3. 자교비율 그래프 \n")
cat("\n\n")

myschool <- read.csv('./rawdatas/myschool.csv') %>%
  filter(癤퓋choolindex == 1) %>% select(m14, o14, m15, o15, m16, o16, m17, o17)

myschool1 <- gather(myschool) %>% 
  mutate(group=substr(key,1,1),year=substr(key,2,3))

myschoolbarplot <- ggplot(myschool1,aes(x=year, y=value, fill = group)) + 
  geom_bar(stat='identity', position = 'dodge', width = 0.5) + 
  geom_text(aes(x=year, y=value, label = paste0(value)),vjust=-0.5, position = position_dodge(0.5),
            family="KoPubBatang Light") + 
  scale_x_discrete(labels=seq(2014,2017,1)) +
  theme_minimal() + 
  theme(axis.ticks = element_blank(),axis.title = element_blank(), 
        axis.text.y = element_blank(), panel.grid.major.x = element_blank(), 
        panel.grid.major.y = element_line(color = 'gray'), 
        panel.grid.minor.y = element_line(color='gray'),
        legend.position="bottom", legend.direction="horizontal", 
        legend.title = element_blank(),legend.text = element_text(family="KoPubBatang Light")) + 
  scale_fill_manual(values = c('#FF00FF','#FFCCFF'), labels = c('자','타'))
myschoolbarplot


#############################################
#               FOREIGN BAR PLOT 외국대학 출신 학생수 그래프
#############################################

cat("\n\n")
cat("\n# 4. 외국대학 출신 학생수 그래프\n")
cat("\n\n")

foreign <- read.csv('./rawdatas/foreign.csv')  %>% 
  rename(schoolindex = 癤퓋choolindex) %>% 
  filter(schoolindex == 1) %>% 
  select(f14, f15, f16, f17) %>% gather()

#foreign

foreign_plot <- ggplot(foreign,aes(key,value)) + geom_bar(stat='identity',width = 0.5, fill='#FF00FF',family="") + 
  geom_text(aes(key,value,label = paste0(value)),vjust=-0.5, family="KoPubBatang Light") + 
  scale_x_discrete(labels=seq(2014,2017,1),) + 
  theme_minimal() + 
  theme(axis.ticks = element_blank(),axis.title = element_blank(), 
        axis.text.y = element_blank(), panel.grid.major.x = element_blank(), 
        panel.grid.major.y = element_line(color = 'gray'), 
        panel.grid.minor.y = element_line(color='gray'))
foreign_plot



##############################################
#                    age rate plot 연령비율 그래프
###########################################

cat("\n\n")
cat("\n# 5. 연령비율 그래프 그래프 \n")
cat("\n\n")



age <- read.csv('./rawdatas/age.csv')%>% 
  filter(schoolindex == 1) %>% 
  select(ends_with('14'),ends_with('15'),ends_with('16'),ends_with('17')) %>% 
  gather() %>% 
  mutate(group = substr(key,1,1),year = substr(key,2,3)) %>%
  ggplot(aes(x=year,y=value,fill=group)) + 
  geom_bar(stat = 'identity', width = 0.5) +
  scale_x_discrete(labels=seq(2014,2017,1))+ 
  theme_minimal() + 
  theme(legend.position="bottom", legend.direction="horizontal", 
        legend.title = element_blank(),legend.text = element_text(family="KoPubBatang Light"),
        axis.title.x = element_blank(), axis.title.y = element_blank(), 
        panel.grid.major.x = element_blank(), panel.grid.major.y = element_line(color = 'gray'), 
        panel.grid.minor.y = element_line(color='gray'), 
        axis.ticks = element_blank(),
        text=element_text(family="KoPubBatang Light")) + 
  scale_fill_manual(values = c('#FF00FF','#FF99ff','#ffccff'), 
                    labels = c('29세 이상','26~28세','25세 이하')) +
  labs(caption = '단위 : %')
age



############################################
#                 FROM SCHOOL 출신학교 현황 그래프 및 글  
############################################
cat("\n\n")
cat("\n# 6. FROM SCHOOL 출신학교 현황 그래프 및 글  \n")
cat("\n\n")
fromschool_data <- read_csv('./rawdatas/fromschool.csv')

school_index <-1

selected_data_fromschool <- fromschool_data %>% filter(schoolindex == 3) %>% group_by(school) %>%
  mutate(tot = sum(y9, y10, y11, y12, y13, y14, y15, y16, y17)) %>% arrange(desc(tot)) %>% distinct(school,tot)

top5 <- selected_data_fromschool %>%  head(5)

etc <- data.frame(school='기타',tot=sum(selected_data_fromschool$tot)-sum(top5$tot))

fromschool <- bind_rows(top5,etc)

fromschool$school <- factor(fromschool$school, levels = rev(as.character(fromschool$school)))

from <- fromschool %>% arrange(school)

text_y <- data.frame(pos = rev(cumsum(fromschool$tot)-fromschool$tot/2))

# data 2 plot

ggplot(from,aes(x='',y=tot,fill=school)) + 
  geom_bar(width = 1, size =1, color = 'white', stat = 'identity') +
  coord_polar('y', start = 0) +
  theme_minimal() + 
  theme(axis.title = element_blank(), axis.text = element_blank(), 
        panel.grid = element_blank(), legend.position = 'none') + 
  scale_fill_brewer() +
  geom_text(aes(label=paste(school,tot), y = text_y), nudge_x = 0.7, family="KoPubBatang Light",size=2)+
  scale_fill_manual(values = c("#FF7FFF", "#FF66FF", "#FF4CFF", "#FF33FF", "#FF1CFF", "#FF00FF"))->
  fromschool_plot
#fromschool 출력
fromschool_plot
cat("\n\n")
cat("\n\n")
#학교 숫자넣기
etc_label <- selected_data_fromschool %>% tail(-5)
a = paste(etc_label$school,'(',etc_label$tot,')', collapse = ', ')

print(a)




```

  